name: Deploy Main

on:
    workflow_dispatch:
    pull_request:
        types: [closed]

jobs:
    deploy-main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Manual Deploy
              if: github.event.pull_request.merged == true
              run: echo "🚀 Deploy finalizado com sucesso"
